name: layoutaction
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - cudatoolkit
  - torchvision
  - numpy
  - scikit-learn
  - scipy
  - pip:
    - tqdm
    - seaborn
    - wandb
    - tabulate
    - ipdb
    - python-pptx
    - pytorch-fid
    - pywebio
    - pycocotools
    - tensorboard